# Generated by Django 4.2 on 2023-05-19 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
